### Lab: Value Iteration in a Grid World

### University of Virginia
### Reinforcement Learning
#### Last updated: May 26, 2025

---

#### Instructions:

Implement value iteration for a $4 \times 3$ gridworld environment. This will measure the value of each state. A robot in this world can make discrete moves: one step up, down, left or right. These actions are deterministic, meaning that the action selected will be taken with probability 1. There is a terminal state with reward +1 in the bottom right corner. All other states have reward 0. The discount factor is 0.9. Use tolerance $\theta=0.01$. Show all code and results.

**Note**: Do not use libraries from `networkx`, `gym`, `gymnasium` when solving this problem.

#### Total Points: 12

---

#### 1) **(POINTS: 2)** As part of your solution, create a GridWorld class with these attributes:

- `nrows` : number of rows in the grid
- `ncols` : number of columns in the grid

and these methods:

- `value_iteration()` with behavior described in [2] below
- `get_reward()` : given the agent row and column, return the reward

The class may include additional attributes and methods as well.

Create an instance using the class, and call `nrows`, `ncols`, and `get_reward()` to verify correctness.

You will not be graded on the implementation of `value_iteration()` for this problem.

#### 2) **(POINTS: 8)** Here, you will be graded on the implementation of `value_iteration()`.
Call `value_iteration()` to calculate and return the value function array. For each sweep over the states, have the function print out the intermediate array.


#### Enter all code here (you may also use multiple cells)

In [7]:
import numpy as np

class GridWorld:
    def __init__(self, nrows, ncols):
        self.nrows = nrows
        self.ncols = ncols
        self.grid = np.zeros((nrows, ncols))

    def get_reward(self, row, col):
        # Terminal state with reward +1 in the bottom right corner
        if row == self.nrows - 1 and col == self.ncols - 1:
            return 1
        # All other states have reward 0
        return 0

    def value_iteration(self, theta=0.01, discount_factor=0.9):
        value_func_array = np.zeros((self.nrows, self.ncols))

        print("Initial Value Function:\n", value_func_array)

        iteration = 0
        while True:
            iteration += 1
            delta = 0
            new_value_func_array = np.copy(value_func_array)

            for row in range(self.nrows):
                for col in range(self.ncols):
                    if row == self.nrows - 1 and col == self.ncols - 1:
                        continue

                    action_values = []

                    if row > 0:
                        action_values.append(self.get_reward(row - 1, col) + discount_factor * value_func_array[row - 1, col])
                    else:
                        action_values.append(self.get_reward(row, col) + discount_factor * value_func_array[row, col])

                    if row < self.nrows - 1:
                        action_values.append(self.get_reward(row + 1, col) + discount_factor * value_func_array[row + 1, col])
                    else:
                        action_values.append(self.get_reward(row, col) + discount_factor * value_func_array[row, col])

                    if col > 0:
                        action_values.append(self.get_reward(row, col - 1) + discount_factor * value_func_array[row, col - 1])
                    else:
                        action_values.append(self.get_reward(row, col) + discount_factor * value_func_array[row, col])

                    if col < self.ncols - 1:
                        action_values.append(self.get_reward(row, col + 1) + discount_factor * value_func_array[row, col + 1])
                    else:
                        action_values.append(self.get_reward(row, col) + discount_factor * value_func_array[row, col])

                    if action_values:
                        best_action_value = max(action_values)
                        new_value_func_array[row, col] = best_action_value
                    else:
                        pass

                    delta = max(delta, abs(new_value_func_array[row, col] - value_func_array[row, col]))

            value_func_array = np.copy(new_value_func_array)

            print(f"\nIteration {iteration}:\n", value_func_array)

            if delta < theta:
                break

        print("\nValue Iteration Converged.")
        return value_func_array


#### 1) Create and test the class

In [8]:
myGW = GridWorld(4, 3)
print(myGW.nrows)
print(myGW.ncols)
print(myGW.get_reward(3, 2))

4
3
1


#### 2) Run value iteration

In [9]:
myGW.value_iteration()

Initial Value Function:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Iteration 1:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]

Iteration 2:
 [[0.  0.  0. ]
 [0.  0.  0.9]
 [0.  0.9 1. ]
 [0.9 1.  0. ]]

Iteration 3:
 [[0.   0.   0.81]
 [0.   0.81 0.9 ]
 [0.81 0.9  1.  ]
 [0.9  1.   0.  ]]

Iteration 4:
 [[0.    0.729 0.81 ]
 [0.729 0.81  0.9  ]
 [0.81  0.9   1.   ]
 [0.9   1.    0.   ]]

Iteration 5:
 [[0.6561 0.729  0.81  ]
 [0.729  0.81   0.9   ]
 [0.81   0.9    1.    ]
 [0.9    1.     0.    ]]

Iteration 6:
 [[0.6561 0.729  0.81  ]
 [0.729  0.81   0.9   ]
 [0.81   0.9    1.    ]
 [0.9    1.     0.    ]]

Value Iteration Converged.


array([[0.6561, 0.729 , 0.81  ],
       [0.729 , 0.81  , 0.9   ],
       [0.81  , 0.9   , 1.    ],
       [0.9   , 1.    , 0.    ]])

#### 3) **(POINTS: 2)** Based on the value function: After the agent has moved right or down, does it ever make sense for it to backtrack (move up or left)? Explain your reasoning.

Since every time the agent moves right or down led to states with higher value, hence it wouldn't make sense to backtrack.